# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
os:
  - linux
  - osx
r:
  - 3.3
  - oldrel
  - release
  - devel
sudo: false
cache: packages

after_success:
    - Rscript -e 'covr::codecov()'
